import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from 'react';
import { BsSearch } from 'react-icons';

export default function Home() {

  const [ city, setCity ] = useState('');
  const [ weather, setWeather ] = useState({});
  const [ loading, setLoading ] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=toronto&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => (
      console.log(response.data),
      setWeather(response.data)
    ))
    setCity('')
    setLoading(false)
  };

  return (
    <div>
      <Head>
        <title>Weather Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={fetchWeather}>Fetch Data</button>
      <h1>Hello</h1> 
    </div>
  )
}
